### PR TITLE
Added typings to package.json

### PR DESCRIPTION
**Pull request by robinchow**
Updated package.json to point to location of typescript declaration files

### CODE REVIEW

**Review by nvie — COMMENTED** [review]
Thanks for the contribution, @robinchow!

Curious! Quite surprised this didn't exist yet, because this works perfectly fine in TypeScript in all cases I know about (apparently, it picks up `index.d.ts` automatically?)

Out of curiosity, did you run into any problems by not having this?

This repo uses a custom build script that will produce a slimmed-down `package.json` right before publishing to NPM, so I'll need to make some more changes for this to work properly.

**Comment by robinchow** [comment]
@nvie Yes I did run into problems - for some reason my project setup would try to use the `index.js`? file:

`Could not find a declaration file for module 'decoders'. '[project_folder]/node_modules/decoders/index.js' implicitly has an 'any' type.`

However, when I pare all the config down, the issue disappears. So it's likely just a me thing. Happy to explore a bit more first about my setup before you change anything on your end.

**Comment by robinchow** [comment]
@nvie I may have found why it doesn't work for me. I'm using typescript 4.1.6 in my main project, and that seems to be what's causing the issue.

I've created a sample project that illustrates the problem, and a workaround if I remain on TS 4.1. The issue seems to resolve in TS 4.2 (and probably onwards)

https://github.com/robinchow/decoders-typings-import-example

**Comment by nvie** [comment]
@robinchow Thanks for contributing! I've just published version [2.0.3](https://github.com/nvie/decoders/releases/v2.0.3) that uses this explicit type pointer. This should have been there from the start! 🙏

**Pull request closed without merging**
